markdown: rdiscount
permalink: /:year/:month/:title/
url: http://oliveryang.net
author: Oliver Yang
description: This article may cover Linux, Kernel, Storage, Network, Hardware, Virtualization and Cloud Computing.
highlighter: pygments
paginate: 24
